"de_killhouse"
{
	"name"	"de_killhouse"
	"imagename"	"de_killhouse"
	"t_arms"	"models/weapons/t_arms_balkan.mdl"
	"ct_arms"	"models/weapons/ct_arms_sas.mdl"
	"t_models"
	{
		"tm_balkan_varianta"""
		"tm_balkan_variantb"""
		"tm_balkan_variantc"""
		"tm_balkan_variantd"""
		"tm_balkan_variante"""
}
	"ct_models"
	{
		"ctm_sas"""
		"ctm_sas_variantA"""
		"ctm_sas_variantB"""
		"ctm_sas_variantC"""
		"ctm_sas_variantD"""
	}
}
//Map by Mitrichone